version: '2'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: tripbuilder:latest
    ports:
    - "9024:22"
    links:
    - redis
    - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    image: tripbuilder:nginx
    ports:
    - "8080:80"
    volumes_from:
    - app
    links:
    - app

  redis:
    image: redis
    ports:
    - 6379:6379

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: jqbdui1bdb
      POSTGRES_USER: tripbuilder
      POSTGRES_DB: tripbuilder
    ports:
      - 5432:5432
